"""initial schema

Revision ID: 276e9d4ad3b6
Revises: 
Create Date: 2026-08-08 23:54:42.425205
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '276e9d4ad3b6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_slug'), ['slug'], unique=True)

    op.create_table('complaints',
    sa.Column('reference_code', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('reporter_name', sa.String(length=160), nullable=True),
    sa.Column('reporter_contact', sa.String(length=160), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('category', sa.Enum('road', 'water', 'waste', 'electricity', 'drainage', 'safety', 'other', name='complaintcategory', native_enum=False, length=24), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='complaintpriority', native_enum=False, length=16), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_output', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('ai_overridden', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('open', 'assigned', 'in_progress', 'resolved', 'rejected', name='complaintstatus', native_enum=False, length=24), nullable=False),
    sa.Column('assigned_department_id', sa.Uuid(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duplicate_of_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['complaints.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaints_assigned_department_id'), ['assigned_department_id'], unique=False)
        batch_op.create_index('ix_complaints_category_priority', ['category', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_reference_code'), ['reference_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_complaints_resolved_at'), ['resolved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_status'), ['status'], unique=False)
        batch_op.create_index('ix_complaints_status_created', ['status', 'created_at'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'staff', name='userrole', native_enum=False, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('status_events',
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('open', 'assigned', 'in_progress', 'resolved', 'rejected', name='complaintstatus', native_enum=False, length=24), nullable=True),
    sa.Column('to_status', sa.Enum('open', 'assigned', 'in_progress', 'resolved', 'rejected', name='complaintstatus', native_enum=False, length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=160), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_events_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_events_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_status_events_complaint_id'))

    op.drop_table('status_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index('ix_complaints_status_created')
        batch_op.drop_index(batch_op.f('ix_complaints_status'))
        batch_op.drop_index(batch_op.f('ix_complaints_resolved_at'))
        batch_op.drop_index(batch_op.f('ix_complaints_reference_code'))
        batch_op.drop_index(batch_op.f('ix_complaints_location'))
        batch_op.drop_index(batch_op.f('ix_complaints_created_at'))
        batch_op.drop_index('ix_complaints_category_priority')
        batch_op.drop_index(batch_op.f('ix_complaints_assigned_department_id'))

    op.drop_table('complaints')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_slug'))
        batch_op.drop_index(batch_op.f('ix_departments_created_at'))

    op.drop_table('departments')
    # ### end Alembic commands ###
